### ISSUE TITLE
corresponding article

### ISSUE THREAD

**Issue by yangzi1234** [XinyaoQiu/DRL-for-edge-computing#2]
Could you please tell me where to find articles related to the code?

**Comment by XinyaoQiu** [comment]
You can search in [Google Scholar](https://scholar.google.com/) or in [IEEE](https://www.ieee.org/).
I would recommend you an article [TMC_DRL](https://ieeexplore.ieee.org/abstract/document/9573404), it's useful for me to write these codes.

**Comment by yangzi1234** [comment]
> You can search in [Google Scholar](https://scholar.google.com/) or in [IEEE](https://www.ieee.org/). I would recommend you an article [TMC_DRL](https://ieeexplore.ieee.org/abstract/document/9573404), it's useful for me to write these codes.

thank you
