### ISSUE TITLE
the reward value

### ISSUE THREAD

**Issue by yangzi1234** [XinyaoQiu/DRL-for-edge-computing#3]
Excuse me, I want to know why the reward value is negative?

**Comment by XinyaoQiu** [comment]
The reward value is the weighted average of the video quality $\phi$ and the energy consumed $E$, and the negative value means one or both of the local $\phi$ and $E$ is/are smaller than offloading $\phi$ and $E$. The reward value will converge to a positive value if we train in enough epochs.

The details are in our article. The reward equation is [14].

**Comment by yangzi1234** [comment]
Thanks for your reply---- Replied Message ***@***.***>Date07/01/2023 19:06 ***@***.***> ***@***.***>***@***.***>SubjectRe: [XinyaoQiu/DRL-for-edge-computing] the reward value (Issue #3)
The reward value is the weighted average of the video quality $\phi$ and the energy consumed $E$, and the negative value means one or both of the local $\phi$ and $E$ is/are smaller than offloading $\phi$ and $E$. The reward value will converge to a positive value if we train in enough epochs.
The details are in our article. The reward equation is [14].

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/XinyaoQiu/DRL-for-edge-computing/issues/3#issuecomment-1615851639",
"url": "https://github.com/XinyaoQiu/DRL-for-edge-computing/issues/3#issuecomment-1615851639",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
